### ISSUE TITLE
Destroyed texture

### ISSUE THREAD

**Issue by ionkrutov** [mattscar/webgpu_book#1]
Hello! 

When I ran the **Ch06_SimpleTexture** I got an error in the console. 

```
Destroyed texture [Texture (unlabeled 400x400 px, TextureFormat::BGRA8Unorm)] used in a submit.
 - While calling [Queue].Submit([[CommandBuffer]])
```
How can I fix this?

**Comment by mattscar** [comment]
Hi Ion,

I don't know, but I'll certainly look into this.

Thanks,
Matt

**Comment by ionkrutov** [comment]
Many thanks!

**Comment by mattscar** [comment]
Hi Ion,

I just uploaded new code to Github for the Ch06_SimpleTexture and Ch07_Text
projects.

I hadn't seen the "Destroyed texture" issue when I wrote the book. Thank
you for bringing it to my attention.

Best,
Matt

**Comment by ionkrutov** [comment]
Hello Matt!

Thank you a lot! It works fine on Windows 11 with several browsers (Edge and Google Chrome/Brave).

FYI, there are several drawbacks on Ubuntu 24. Additional flags need to be added like `--enable-features=Vulkan—-enable-feature=SkiaGraphite` and resolve other issues. 

Kind regards, 
Ion.

**Comment by mattscar** [comment]
Hi Ion,

That's very interesting. I ran the code on multiple browsers, but I didn't
run anything on Ubuntu. I'll give that a try.

Thanks again,
Matt

**Comment by ionkrutov** [comment]
Hello Matt! 

I'll add a few more comments, maybe they will help someone. My laptop has two video cards - one integrated into the processor, the other Nvidia. When the browser starts, it starts using the resources of the integrated video card, so you can get an error like
```
vkAllocateMemory failed with VK_ERROR_OUT_OF_DEVICE_MEMORY
- While handling unexpected error type Internal when allowed errors are (Validation|DeviceLost).
```
In order to run on the discrete video card, you can add the environment variable `DRI_PRIME=1`

```bash
DRI_PRIME=1 google-chrome --enable-features=Vulkan.
```

Kind regards,
Ion.
